[versions]
androidGradlePlugin = "8.7.2"
androidx-room = "2.6.1"
androidxActivity = "1.9.3"
androidxComposeCompiler = "1.5.14"
androidxComposeMaterial3 = "1.3.1"
androidxComposeUi = "1.7.5"
androidxCore = "1.15.0"
androidxEspresso = "3.6.1"
androidxHilt = "1.2.0"
androidxLifecycle = "2.8.7"
androidxNavigation = "2.8.0-rc01"
androidxTestCore = "1.5.0"
androidxTestExt = "1.1.5"
androidxTestRules = "1.5.0"
androidxTestRunner = "1.6.2"
com-squareup-retrofit2 = "2.11.0"
coroutines = "1.9.0"
firebase-bom = "32.1.1"
firebase-crashlytics-gradle = "3.0.1"
hilt = "2.52"
junit = "4.13.2"
kotlin = "2.1.0"
kotlinxSerializationJson = "1.6.3"
ksp = "2.1.0-1.0.29"
mock-webserver = "4.11.0"
mockk = "1.13.5"
moshi = "1.15.1"
moshi-converter = "2.11.0"
turbine = "1.2.0"
googleAccompanist = "0.36.0"
loggingInterceptor = "4.12.0"
appcompat = "1.7.0"
material = "1.12.0"
playServicesLocation = "21.3.0"
lottie = "6.6.0"
googleGmsGoogleServices = "4.4.2"
detekt = "1.23.7"
mapsCompose = "6.2.1"
playServicesMaps = "19.0.0"
secrets = "2.0.1"
places = "4.0.0"
coil = "2.7.0"
splashScreen = "1.0.1"
junit5Api = "5.10.0"
junit5Extensions = "1.6.0"
junit5Compose = "1.4.0"
junit5Plugin = "1.11.2.0"
junit5Runner = "1.4.0"
materialIcons = "1.7.7"
constraintLayout = "1.1.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidxComposeUi" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidxComposeUi" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidxComposeUi" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidxComposeUi" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidxComposeUi" }
androidx-compose-permission = { module = "com.google.accompanist:accompanist-permissions", version.ref = "googleAccompanist" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHilt" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigation" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTestCore" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspresso" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTestRules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
com-squareup-okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
com-squareup-retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "com-squareup-retrofit2" }
com-squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "com-squareup-retrofit2" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
io-arrow-kt-arrow-core = "io.arrow-kt:arrow-core:1.1.5"
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
mock-webserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mock-webserver" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
moshi-converter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "moshi-converter" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
kotlin-coroutines-play = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
places = { module = "com.google.android.libraries.places:places", version.ref = "places" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
splash-screen = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5Api" }
junit5-extensions = { module = "de.mannodermaus.junit5:android-test-extensions", version.ref = "junit5Extensions" }
junit5-compose = { module = "de.mannodermaus.junit5:android-test-compose", version.ref = "junit5Compose" }
junit5-runner = { module = "de.mannodermaus.junit5:android-test-runner", version.ref = "junit5Runner" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5Api" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIcons" }
constraint-layout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintLayout"}

[bundles]
com-squareup-retrofit2 = [
    "com-squareup-okhttp3-logging-interceptor",
    "com-squareup-retrofit2-converter-gson",
    "com-squareup-retrofit2-retrofit",
]
moshi = [
    "moshi",
    "moshi-converter",
    "moshi-kotlin",
]
testing = [
    "mockk",
    "turbine",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
firebase-crashlitycs = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-gradle" }
hilt-gradle = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
gms = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "junit5Plugin" }


